// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLXMvu3MiMIhAIml3Pcv9sVSRpbmgYZyc',
    appId: '1:754414634472:web:7d00a91f45e0c12e41905d',
    messagingSenderId: '754414634472',
    projectId: 'smart-bite6',
    authDomain: 'smart-bite6.firebaseapp.com',
    storageBucket: 'smart-bite6.firebasestorage.app',
    measurementId: 'G-7HG4569J16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5gGPBZYfFWetg8orM_TfIB5IlGcGwdas',
    appId: '1:754414634472:android:0fa497a7fef6a76641905d',
    messagingSenderId: '754414634472',
    projectId: 'smart-bite6',
    storageBucket: 'smart-bite6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4myrBge4Sd9oudCYIlX0Dyc7a1ol-4Jk',
    appId: '1:754414634472:ios:3a3b173cb1a8e60341905d',
    messagingSenderId: '754414634472',
    projectId: 'smart-bite6',
    storageBucket: 'smart-bite6.firebasestorage.app',
    iosBundleId: 'com.example.smartBite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4myrBge4Sd9oudCYIlX0Dyc7a1ol-4Jk',
    appId: '1:754414634472:ios:3a3b173cb1a8e60341905d',
    messagingSenderId: '754414634472',
    projectId: 'smart-bite6',
    storageBucket: 'smart-bite6.firebasestorage.app',
    iosBundleId: 'com.example.smartBite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLXMvu3MiMIhAIml3Pcv9sVSRpbmgYZyc',
    appId: '1:754414634472:web:66b60fcc1f1da25a41905d',
    messagingSenderId: '754414634472',
    projectId: 'smart-bite6',
    authDomain: 'smart-bite6.firebaseapp.com',
    storageBucket: 'smart-bite6.firebasestorage.app',
    measurementId: 'G-06W3VBD49D',
  );
}
